# workflow yaml code
name:
on:
	push:
		branches:
			- 'master'
		tags:
			- '**'
jobs: 
	push: 
		runs-on: ubuntu-lates
		steps:
			- name:
				uses: actions/checkout@v2
			- name: Docker meta
				id: docker_meta
				uses: crazy-max/ghaction-docker-meta@v1 
				with:
					images: leecloudo/nodejs-ci 
					tag-semver: | 
						{{version}}
						{{major}}.{{minor}}
			- name: 
				uses: docker/setup-qemu-action@v2 을

			- name: Set up Docker Buildx 
				uses: docker/setup-buildx-action@v2 
			- name: Login to Docker Hub
				uses: docker/login-action@v2 
				with: # 동작에 사용할 input 값 사용 선언
					username: ${{ secrets.DOCKER_HUB_USERNAME }} 
					password: ${{ secrets.DOCKER_HUB_PASSWORD }}
			- name: Build and push Docker Image
				uses: docker/build-push-action@v4
				with:
					context: .
					push: true 
					tags: ${{ steps.docker_meta.outputs.tags }}
					labels: ${{ steps.docker_meta.outputs.labels }}
